play.http.secret.key = "changeme-journey-validator-example"

play.i18n.langs = ["en"]

play.filters.enabled = []

journey.storage.url = "http://localhost:9000"
journey.storage.url = ${?JOURNEY_STORAGE_URL}

journey.serviceName = "example-survey"
journey.serviceName = ${?JOURNEY_SERVICE_NAME}
